name: advds
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - ipykernel
  - ipython
  - nbformat
  - nbconvert
  - notebook
  - jupyterlab
  - plotly
  - streamlit
  - geopandas
  - shapely
  - fiona
  - pyarrow
  - requests
  - beautifulsoup4
  - pyyaml
  - pillow
  - watchdog
  - pip
  - pip:
      - torch>=2.6
      - torchvision
      - torchaudio
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - yfinance
      - pandas-market-calendars
      - google-cloud-bigquery
      - exchange-calendars
      - curl-cffi
      - transformers
      - tqdm
      - xgboost
      - lightgbm